### ISSUE TITLE
Goal & Roadmap

### ISSUE THREAD

**Issue by ci010** [ci010/DeskGap#1]
The main purpose of this fork is to swap the [xmcl](https://github.com/Voxelum/x-minecraft-launcher) runtime from electron to deskgap.

So, the goal of this fork is implementing the APIs used by the xmcl, and these APIs implementations will **TRY** to be compatible with electron API.

The high priority APIs to implement:
- [ ] Tray, [use case](https://github.com/Voxelum/x-minecraft-launcher/blob/master/xmcl-electron-app/main/controllers/tray.ts), the tray will only support icon via file path for ico on win32, icns on mac, and png on linux.
  - [x] win32
  - [ ] mac
  - [ ] linux
- [ ] app.setAsDefaultProtocolClient
  - [x] win32
  - [ ] mac
  - [ ] linux
- [ ] app.requestSingleInstanceLock
  - [x] win32
  - [ ] mac
  - [ ] linux
- [ ] app.isDefaultProtocolClient
  - [x] win32
  - [ ] mac
  - [ ] linux
- [ ] app.getLocale
  - [x] win32
  - [ ] mac
  - [ ] linux
- [ ] app.relaunch
  - [ ] win32
  - [ ] mac
  - [ ] linux
- [ ] win32 window background color (with alpha transparency)

The low priority APIs, which might be dropped if I don't have time:
- [ ] #2
- [ ] setProgressBar, [use case](https://github.com/Voxelum/x-minecraft-launcher/blob/master/xmcl-electron-app/main/controllers/taskProgress.ts).
